version: '2'
services:
  db12:
    image: postgres:10.0
    networks:
      - pg12
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db12-data:/var/lib/postgresql/data/pgdata
    restart: unless-stopped             # run as a service

  odoo12:
    image: odoo:12.0
    networks:
      - pg12
    depends_on:
      - db12
    ports:
      - "12000:8069"
        #  - "12071:8071"  
    tty: true
    command: -- --dev=reload
    volumes:
      - ./etc:/etc/odoo
      - odoo-web12-data:/var/lib/odoo
      # - ~/odoo/add13/addons:/mnt/extra-addons
      - ~/odoo/add12/reporting-engine:/mnt/reporting-engine
      - ~/odoo/add12/server-tools:/mnt/server-tools
      - ~/odoo/add12/server-ux:/mnt/server-ux
      - ~/odoo/add12/stock-logistics-workflow:/mnt/stock-logistics-workflow
      - ~/odoo/add12/stock-logistics-warehouse:/mnt/stock-logistics-warehouse
      - ~/odoo/add12/stock-logistics-barcode:/mnt/stock-logistics-barcode
      - ~/odoo/add12/prune12:/mnt/prune12
      # - ~/odoo/add13/prune-nle:/mnt/prune-nle
      # - ~/odoo/add13/prune-nle:/mnt/prune-nle
      # - ~/odoo/add13/product-variant:/mnt/product-variant
      # - ~/odoo/add13/account-analytic:/mnt/account-analytic
      - ~/odoo/add12/stock-logistics-transport:/mnt/stock-logistics-transport
      # - ~/odoo/add13/purchase-workflow:/mnt/purchase-workflow
      # - ~/odoo/add13/sale-workflow:/mnt/sale-workflow
      # - ~/odoo/add13/product-attribute:/mnt/product-attribute
      - ~/odoo/add12/web:/mnt/web
      # - ~/odoo/add13/mis-builder:/mnt/mis-builder
      # - ~/odoo/add13/account-financial-reporting:/mnt/account-financial-reporting 
      # - ~/odoo/add13/partner-contact:/mnt/partner-contact
      # - ~/odoo/add13/account-invoicing:/mnt/account-invoicing
      # - ~/odoo/add13/intrastat:/mnt/intrastat
      # - ~/odoo/add13/contract:/mnt/contract
      # - ~/odoo/add12/operating-unit:/mnt/operating-unit --> masih error
      # - ~/odoo/add13/manufacture:/mnt/manufacture
    restart: unless-stopped             # run as a service
networks:
    pg12: 
        driver: bridge
volumes:
    odoo-db12-data:
    odoo-web12-data:        
